sonar.projectKey=guilhermezica_SIT223-7.3HD
sonar.organization=guilhermezica
sonar.sources=frontend/src,backend
sonar.exclusions=**/node_modules/**,**/dist/**,backend/public/**,backend/tests/**,backend/junit.xml
sonar.tests=backend/tests
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
